//! Neovim.
//!
//! A file dropped into `after/plugin` is sourced on every start without the
//! user adding a `require` anywhere, which makes it the one place a tool can
//! install itself into a config it does not own. It is also the one place a
//! user can uninstall it from: deleting the file removes the integration
//! completely, and the file says so in its first line.

use super::{on_path, Plan, Step};
use std::path::{Path, PathBuf};

/// The generated file, kept under its own name so nothing else is at risk.
const SCRIPT: &str = "after/plugin/howmany.lua";

/// Written into the file so a later run can tell its own output from a file
/// the user has since taken over.
const MARKER: &str = "-- generated by `howmany init`";

/// Where Neovim reads its configuration from.
///
/// Not `dirs::config_dir`, which on macOS answers `~/Library/Application
/// Support` -- Neovim follows the XDG layout on every Unix, macOS included, and
/// a file written to the Apple location is a file it never reads.
fn config_dir() -> Option<PathBuf> {
    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME").filter(|dir| !dir.is_empty()) {
        return Some(PathBuf::from(xdg).join("nvim"));
    }
    if cfg!(windows) {
        return dirs::data_local_dir().map(|dir| dir.join("nvim"));
    }
    Some(dirs::home_dir()?.join(".config").join("nvim"))
}

/// Whether Neovim is installed, and if so whether it is already wired up.
/// [`None`] means it is not installed.
pub fn state() -> Option<bool> {
    let config = config_dir()?;
    let installed = on_path("nvim").is_some() || config.exists();
    installed.then(|| config.join(SCRIPT).exists())
}

pub fn setup(plan: &Plan, named: bool) -> Vec<Step> {
    let Some(config) = config_dir() else {
        return vec![Step::Skipped(
            "no configuration directory for this account".to_string(),
        )];
    };

    // An existing config directory counts as installed even without `nvim` on
    // PATH, because plenty of people launch it from a wrapper or an alias.
    if on_path("nvim").is_none() && !config.exists() && !named {
        return vec![Step::Skipped("nvim is not installed".to_string())];
    }

    let script = config.join(SCRIPT);
    let wanted = render(plan.binary);

    match std::fs::read_to_string(&script) {
        Ok(existing) if existing == wanted => {
            return vec![Step::Unchanged(format!("{} is current", script.display()))]
        }
        Ok(existing) if !existing.contains(MARKER) && !plan.force => {
            return vec![Step::Skipped(format!(
                "{} was not written by howmany; pass --force to replace it",
                script.display()
            ))]
        }
        _ => {}
    }

    vec![match plan.write(&script, &wanted) {
        Ok(()) if plan.dry_run => Step::Changed(format!("would write {}", script.display())),
        Ok(()) => Step::Changed(format!("wrote {}", script.display())),
        Err(err) => Step::Failed(format!("could not write {}: {err}", script.display())),
    }]
}

/// The Lua that starts the server and keeps its lenses drawn.
///
/// Neovim never refreshes code lenses on its own -- a server can publish all it
/// likes and nothing appears until something calls `refresh` -- so the file
/// wires that up too. Without it the integration looks broken rather than off.
fn render(binary: &Path) -> String {
    let quoted = lua_string(&binary.to_string_lossy());

    format!(
        r#"{MARKER}
-- Delete this file to remove the integration; `howmany init` will restore it.

local binary = {quoted}
if vim.fn.executable(binary) == 0 then
  return
end

local group = vim.api.nvim_create_augroup("howmany", {{ clear = true }})

vim.api.nvim_create_autocmd({{ "BufReadPost", "BufNewFile" }}, {{
  group = group,
  callback = function(args)
    -- Real files only: a terminal, a help page or a plugin's scratch buffer
    -- has no line count worth reporting.
    if vim.bo[args.buf].buftype ~= "" then
      return
    end

    local root
    if vim.fs.root then
      root = vim.fs.root(args.buf, {{ ".git" }})
    end

    vim.lsp.start({{
      name = "howmany",
      cmd = {{ binary, "lsp" }},
      root_dir = root or vim.fn.getcwd(),
    }}, {{ bufnr = args.buf }})
  end,
}})

vim.api.nvim_create_autocmd("LspAttach", {{
  group = group,
  callback = function(args)
    local client = vim.lsp.get_client_by_id(args.data.client_id)
    if not client or client.name ~= "howmany" then
      return
    end

    -- Neovim 0.12 keeps enabled lenses current by itself and deprecated the
    -- manual refresh; before that, nothing is drawn until something asks.
    if vim.lsp.codelens.enable then
      vim.lsp.codelens.enable(true, {{ bufnr = args.buf }})
      return
    end

    vim.api.nvim_create_autocmd({{ "BufEnter", "InsertLeave", "TextChanged" }}, {{
      group = group,
      buffer = args.buf,
      callback = function()
        vim.lsp.codelens.refresh({{ bufnr = args.buf }})
      end,
    }})
    vim.lsp.codelens.refresh({{ bufnr = args.buf }})
  end,
}})
"#
    )
}

/// A Lua string literal holding `value`.
///
/// A path can contain a quote or a backslash, and generating a config file that
/// does not parse would break every plugin loaded after it.
fn lua_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_script_names_the_binary_and_the_subcommand() {
        let lua = render(Path::new("/opt/howmany"));
        assert!(lua.contains(r#"local binary = "/opt/howmany""#), "{lua}");
        assert!(lua.contains(r#"cmd = { binary, "lsp" }"#), "{lua}");
    }

    /// The file has to be recognizable as ours on the next run, and removable
    /// by a user who has never read our documentation.
    #[test]
    fn the_script_says_where_it_came_from_and_how_to_remove_it() {
        let lua = render(Path::new("/opt/howmany"));
        assert!(lua.starts_with(MARKER));
        assert!(lua.contains("Delete this file"));
    }

    /// Lenses that are never enabled or refreshed are lenses nobody sees, and
    /// which call does that depends on the Neovim version -- so the script has
    /// to carry both.
    #[test]
    fn the_script_turns_code_lenses_on_however_old_neovim_is() {
        let lua = render(Path::new("/opt/howmany"));
        assert!(lua.contains("vim.lsp.codelens.enable"), "{lua}");
        assert!(lua.contains("vim.lsp.codelens.refresh"), "{lua}");
    }

    #[test]
    fn a_path_with_quotes_or_backslashes_stays_a_valid_literal() {
        assert_eq!(lua_string(r#"/a/b"c"#), r#""/a/b\"c""#);
        assert_eq!(
            lua_string(r"C:\bin\howmany.exe"),
            r#""C:\\bin\\howmany.exe""#
        );
    }

    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(
            render(Path::new("/opt/howmany")),
            render(Path::new("/opt/howmany")),
            "two runs must agree, or init can never report 'unchanged'"
        );
    }

    /// Neovim reads `~/.config/nvim` on macOS like every other Unix, so the
    /// path must not come from the platform's own notion of a config directory.
    #[test]
    fn the_config_directory_is_the_xdg_one() {
        let found = config_dir().expect("a home directory is assumed");
        assert!(found.ends_with("nvim"), "{}", found.display());

        if std::env::var_os("XDG_CONFIG_HOME").is_none() && !cfg!(windows) {
            assert!(
                found.ends_with(".config/nvim"),
                "expected ~/.config/nvim, got {}",
                found.display()
            );
        }
    }

    #[test]
    fn a_different_binary_produces_a_different_script() {
        assert_ne!(
            render(Path::new("/opt/howmany")),
            render(Path::new("/usr/bin/howmany"))
        );
    }
}
